---

name: rust-audit

on:
  pull_request:
    paths:
      - '.github/workflows/rust-audit.yml'
      - 'Cargo.toml'
      - 'Cargo.lock'
  push:
    branches:
      - main
      - wip/next
    paths:
      - '.github/workflows/rust-audit.yml'
      - 'Cargo.toml'
      - 'Cargo.lock'
  schedule:
    - cron: '0 6 * * 1'

jobs:
  call-workflow:
    uses: wookietreiber/workflows/.github/workflows/rust-cargo-audit.yml@main
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}

...
