---

name: rust

on:
  pull_request:
    paths:
      - '.github/workflows/rust.yml'
      - '.rustfmt.toml'
      - 'rust-toolchain.toml'
      - 'Cargo.toml'
      - 'Cargo.lock'
      - '**.rs'
  push:
    branches:
      - main
      - wip/next
    paths:
      - '.github/workflows/rust.yml'
      - '.rustfmt.toml'
      - 'rust-toolchain.toml'
      - 'Cargo.toml'
      - 'Cargo.lock'
      - '**.rs'

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  call-workflow:
    uses: wookietreiber/workflows/.github/workflows/rust.yml@main

...
